name = "luabased"
version = "1.0.1"  # version has to be kept in sync with ./luakat/init.lua
description = "Extending the base lua library with missing features."
license = "Apache-2.0"
authors = ["Liam Collod <lcollod@gmail.com>"]
readme = "README.md"
repository = "https://github.com/MrLixm/luabased"
keywords = ["opscript", "lua"]
